NumPy (Numerical Python) is the foundational library for numerical computing in Python.

below are some example usage:

In [1]:
import numpy as np
from numpy.matrixlib.defmatrix import matrix

arr_arrange = np.arange(5, 15, 2)
print(arr_arrange)
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)


arr_1d = np.array([1,2,3,4,5,6,7,8,9])
print("1D array")
print(arr_1d)


#
#



[ 5  7  9 11 13]
[0.   0.25 0.5  0.75 1.  ]
1D array
[1 2 3 4 5 6 7 8 9]


In [57]:
slice_1d = arr_1d[::2]
print("1D slice")
print(slice_1d)

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


print("Slice rows [1,2] =\n ", array[1,2])
print("slice rows from zero to one and colums from one to two", array[0:2, 1:3])






1D slice
[1 3 5 7 9]
Slice rows [1,2] =
  6
slice rows from zero to one and colums from one to two [[2 3]
 [5 6]]


In [54]:
array_1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

reshape = array_1.reshape(-1, 3)
print(reshape)

ravelled = np.ravel(array)
print("ravelled: \n", ravelled)


#transpose
transpose_op = matrix.transpose(array_1)
print(transpose_op)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ravelled: 
 [1 2 3 4 5 6 7 8 9]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Fancy indexing

In [53]:
array_1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])


fancy = array_1[[0, 3]]
print(fancy)



[[ 1  2  3]
 [10 11 12]]


boolean indexing

In [ ]:

# age = np.array([10, 10, 15,18, 19])
# adult = age[age >= 18]
# print(adult)




Data types

In [ ]:

arr_float = np.array([1.2, 6.5, 8.9, 3.5])
print("data type of arr_float", arr_float.dtype)


arr_int = arr_float.astype(np.int64)
print("data type of arr_int", arr_int.dtype)




Arithmetic UFUNCS

In [ ]:

x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([4, 5, 6, 7, 8, 9])

print("Add", np.add(x, y))
print("Subtract", np.subtract(x, y))
print("Multiply", np.multiply(x, y))
print("Divide", np.divide(x, y))




Logarithms

In [ ]:
#Logarithm
# arr_for_log = np.array([1, np.e, 100])
# arr_for_log1 = np.log(arr_for_log)
# arr_for_log2 = np.log2(arr_for_log)
# arr_for_log10 = np.log10(arr_for_log)
# print(arr_for_log1)
# print(arr_for_log2)
# print(arr_for_log10)




Exponents

In [ ]:

arr_power = np.array([2,3,4])
print("squared (np.power):", np.power(arr_power, 2))
print("Exponent (np.exp):", np.exp(arr_power) )

#

Trigonometric and hyperbolic UFUNCS

In [ ]:

# angles = np.array([0, np.pi/2, np.pi])
#
# print("Sin:", np.sin(angles))
# print("Cos:", np.cos(angles))
# print("Tan:", np.tan(angles))
#
#
# #hyperbolic
# values = np.array([-1, 0, 1])
# print("\nSin:", np.sinh(values))
# print("Cos:", np.cosh(values))
# print("Tan:", np.tanh(values))




Rounding and Elements-Wise UFUNCS

In [ ]:


data_values = np.array([-1.7, -0.22, 0.33, 1.9, 4.2])

print("Absolute:", np.absolute(data_values))
print("sign:", np.sign(data_values))

print("\nRound:", np.round(data_values))
print("Floor:", np.floor(data_values))
print("Ceil:", np.ceil(data_values))
print("Trunc:", np.trunc(data_values))





Comparison and logical UFUNCS

In [ ]:

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 1, 8])

print("np.less(a,b):", np.less(a,b))
print("np.greater(a,b):", np.greater(a,b))
print("np.not_equal(a,b):", np.not_equal(a,b))
print("np.greater_equal(a,b):", np.greater_equal(a,b))
print("np.equal(a,b):", np.equal(a,b))



#

statistical and aggregational Functions

In [ ]:


stats_arr = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


print("stats_arr: ", stats_arr)


print("\nSum of all elements:", np.sum(stats_arr))
print("mean of all elements:", stats_arr.mean())
print("variance of all elements:", np.var(stats_arr))
print("Standard Deviation of all elements:", np.std(stats_arr))


print("\nmin: ", np.min(stats_arr))
print("max: ", np.max(stats_arr))
print("Argmin: ", np.argmin(stats_arr)) #index of the minimum value
print("Argmax: ", np.argmax(stats_arr)) #index of the maximum value

print("\nMedian: ", np.median(stats_arr))
print("Quantile (0.25): ", np.quantile(stats_arr, 0.25))

#Using axis parameter: sum along rows (axis=1) or columns (axis=0)
print("\nSum along rows: ", np.sum(stats_arr, axis=1))
print("\nSum along columns: ", np.sum(stats_arr, axis=0))





#Broadcasting  Examples



#LINEAR ALGEBRA WITH NUMPHY.LINALG


#Numpy random Module