In [7]:
import numpy as np


arr = np.arange(1,21)
print(arr)

arr2 = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])

print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
